### ISSUE TITLE
OpenCV Error - Can't load the images

### ISSUE THREAD

**Issue by elisim** [orcam-public/datahack2019#3]
Hey,

First, thanks for uploading the data samples, you just forgot to update the README.md according to data folder (add relative paths).

I tried to load the images as described in the README:

```python
from data import Images
with Images('data/images.tar') as images:
    path = images.paths[0]
    image = images[path]
    print('read image "{}"" of shape {}'.format(path, image.shape))
# read image "person_0013/channel_0081/seq_0009/frame_00425.jpg"" of shape (64, 64, 3)
```
and got the following error:

![image](https://user-images.githubusercontent.com/17675462/64128727-ad837800-cdc0-11e9-871d-23707d361af6.png)

**System Information:**
Windows 10
OpenCV version 4.1.0
Python 3.6.8 :: Anaconda, Inc.

**Comment by ypeleg** [comment]
Delete the index pickle and let it reindex.
It solved it for me

**Comment by orcam-public** [comment]
* Fixed the readme and the default data file path to include the "data/" prefix
* Updated the "Images" class, so whenever the index file does not match the tar file (checked during __getitem__) a proper error will be displayed, suggesting user should remove the index file and retry.
