### ISSUE TITLE
Test dataset?

### ISSUE THREAD

**Issue by ypeleg** [orcam-public/datahack2019#4]
Hi!

The test dataset (for the leaderboard) is not mentioned.
Will it just be another tar file without the labels?

Yam

**Comment by orcam-public** [comment]
The published data is just an example of how the data looks. 
The train and test datasets will have the same structure, only that the test dataset will be stripped of the "person" folder. So it will only have video and sequence numbers.
We will publish a small example and update the Readme to make it more clear. 
If it answers your question please close the issue.
Thanks!
