### ISSUE TITLE
Images class parallelisation

### ISSUE THREAD

**Issue by dremovd** [orcam-public/datahack2019#9]
Impossible to control image loading parallelization due to `Images` usage of FileHandlers (which are not serializable).

**Comment by orcam-public** [comment]
You can parallelize the data loading, you just have to make sure each process has its own, locally-initialized, ```Images``` class. It can't be distributed between processes once initialized. 
If you use pytorch I recommend you take a look at the example [here](https://pytorch.org/docs/stable/data.html#torch.utils.data.IterableDataset).
They use ```worker_init_fn``` to solve a similar issue.
